### ISSUE TITLE
Daemon doesn't accept -datadir option

### ISSUE THREAD

**Issue by himikk** [WorldcoinGlobal/WorldcoinDaemon#2]
WorldcoinDaemon accepts -datadir option only at startup:
./WorldcoinDaemon -datadir=data -daemon

When try execute any command, for example:
./WorldcoinDaemon -datadir=data netinfo 
I'm getting an error:
error: You must set rpcpassword=<password> in the configuration file:
/home/xxxxx/.worldcoin/worldcoin.conf
If the file does not exist, create it with owner-readable-only file permissions.

**Comment by Berzeck** [comment]
Hi, a few  observations
1) Data directory should be absolute
2) In the directory where your data chain is created, a file called worldcoin.conf should exist with this content (suggested)

rpcuser=<Chose User Name>
rpcpassword=<Chose password>
rpcport=11082
port=11081
daemon=1
server=1
gen=0
listen=1
testnet=0
maxconnections=100

3) to execute commands type WorldcoinDaemon -datadir=/<path_to_chain>   -conf=/<path_to_chain>/worldcoin.conf    <command>
4) Alternatively you could put every variable that resides in worldcoin.conf file in the command line, example :
WorldcoinDaemon -datadir=/home/xxx/Chain   -conf=/home/xxx/Chain/worldcoin.conf  -rpcpassword=superpassword -rpcuser=superuser  ... netinfo
5) We could provide faster support if you post or PM in official forum  forum.worldcoin.global

Don't hesitate to contact us if you continue to have trouble :)

**Comment by himikk** [comment]
Thank you
Think you should put info about absolute path in command line options to readme

**Comment by Berzeck** [comment]
Will do, thank you for useful feedback!
