### ISSUE TITLE
net.cpp:18:22: fatal error: miniwget.h: No such file or directory

### ISSUE THREAD

**Issue by banjochose** [WorldcoinGlobal/WorldcoinDaemon#3]
net.cpp:18:22: fatal error: miniwget.h: No such file or directory
 #include <miniwget.h>
                      ^
compilation terminated.
make: *** [obj/net.o] Error 1
strip: 'WorldcoinDaemon': No such file

**Comment by Berzeck** [comment]
Hello friend, you need to read the respective file inside Documents 
folder.
In particular, you didn't compile miniunpn library (or compiler didn't 
find the include files)

Mario

**Comment by banjochose** [comment]
Alright thanks.
